package tn.esprit.persistance;
// Generated 19 nov. 2016 13:17:14 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Cadeau generated by hbm2java
 */
@Entity
@Table(name = "cadeau", catalog = "troc")
public class Cadeau implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCadeau;
	private String label;
	private String description;
	private int nbrpoint;
	private int stock;
	private Set<Swapper> swappers = new HashSet<Swapper>(0);

	public Cadeau() {
	}

	public Cadeau(int nbrpoint, int stock) {
		this.nbrpoint = nbrpoint;
		this.stock = stock;
	}

	public Cadeau(String label, String description, int nbrpoint, int stock, Set<Swapper> swappers) {
		this.label = label;
		this.description = description;
		this.nbrpoint = nbrpoint;
		this.stock = stock;
		this.swappers = swappers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cadeau", unique = true, nullable = false)
	public Integer getIdCadeau() {
		return this.idCadeau;
	}

	public void setIdCadeau(Integer idCadeau) {
		this.idCadeau = idCadeau;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "nbrpoint", nullable = false)
	public int getNbrpoint() {
		return this.nbrpoint;
	}

	public void setNbrpoint(int nbrpoint) {
		this.nbrpoint = nbrpoint;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "cadeauswap", catalog = "troc", joinColumns = {
			@JoinColumn(name = "cadeau_id_cadeau", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "swapper_Id", nullable = false, updatable = false) })
	public Set<Swapper> getSwappers() {
		return this.swappers;
	}

	public void setSwappers(Set<Swapper> swappers) {
		this.swappers = swappers;
	}

}
