package tn.esprit.persistance;
// Generated 19 nov. 2016 13:17:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments", catalog = "troc")
public class Comments implements java.io.Serializable {

	private Integer idComments;
	private Forum forum;
	private Swapper swapper;
	private String comment;
	private int note;
	private Date date;

	private static final long serialVersionUID = 1L;

	public Comments() {
	}

	public Comments(Forum forum, Swapper swapper, int note, int forumId) {
		this.forum = forum;
		this.swapper = swapper;
		this.note = note;
		
	}

	public Comments(Forum forum, Swapper swapper, String comment, int note, int forumId) {
		this.forum = forum;
		this.swapper = swapper;
		this.comment = comment;
		this.note = note;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_comments", unique = true, nullable = false)
	public Integer getIdComments() {
		return this.idComments;
	}

	public void setIdComments(Integer idComments) {
		this.idComments = idComments;
	}

	@ManyToOne()
	@JoinColumn(name = "forumID", nullable = false)
	public Forum getForum() {
		return this.forum;
	}

	public void setForum(Forum forum) {
		this.forum = forum;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "swapperID", nullable = false)
	public Swapper getSwapper() {
		return this.swapper;
	}

	public void setSwapper(Swapper swapper) {
		this.swapper = swapper;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "note", nullable = false)
	public int getNote() {
		return this.note;
	}

	public void setNote(int note) {
		this.note = note;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return date;
	}

	public Comments(Forum forum, Swapper swapper, String comment, int note, Date date) {
		super();
		this.forum = forum;
		this.swapper = swapper;
		this.comment = comment;
		this.note = note;
		this.date = date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	

}
