package tn.esprit.persistance;
// Generated 19 nov. 2016 13:17:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exchange generated by hbm2java
 */
@Entity
@Table(name = "exchange", catalog = "troc")
public class Exchange implements java.io.Serializable {

	private Integer idExchange;
	private Goods goodsByIdgooddemande;
	private Goods goodsByIdgoodOffre;
	private int status;
	private Date dateExchange;
	private static final long serialVersionUID = 1L;

	public Exchange() {
	}

	public Exchange(Goods goodsByIdgooddemande, Goods goodsByIdgoodOffre, int status, Date dateExchange) {
		this.goodsByIdgooddemande = goodsByIdgooddemande;
		this.goodsByIdgoodOffre = goodsByIdgoodOffre;
		this.status = status;
		this.dateExchange = dateExchange;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_exchange", unique = true, nullable = false)
	public Integer getIdExchange() {
		return this.idExchange;
	}

	public void setIdExchange(Integer idExchange) {
		this.idExchange = idExchange;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idgooddemande", nullable = false)
	public Goods getGoodsByIdgooddemande() {
		return this.goodsByIdgooddemande;
	}

	public void setGoodsByIdgooddemande(Goods goodsByIdgooddemande) {
		this.goodsByIdgooddemande = goodsByIdgooddemande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idgoodOffre", nullable = false)
	public Goods getGoodsByIdgoodOffre() {
		return this.goodsByIdgoodOffre;
	}

	public void setGoodsByIdgoodOffre(Goods goodsByIdgoodOffre) {
		this.goodsByIdgoodOffre = goodsByIdgoodOffre;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_exchange", nullable = false, length = 19)
	public Date getDateExchange() {
		return this.dateExchange;
	}

	public void setDateExchange(Date dateExchange) {
		this.dateExchange = dateExchange;
	}

}
