package tn.esprit.persistance;
// Generated 19 nov. 2016 13:17:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes", catalog = "troc")
public class Notes implements java.io.Serializable {

	private Integer idNote;
	private Swapper swapper;
	private int note;
	private static final long serialVersionUID = 1L;

	public Notes() {
	}

	public Notes(Swapper swapper, int note) {
		this.swapper = swapper;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_note", unique = true, nullable = false)
	public Integer getIdNote() {
		return this.idNote;
	}

	public void setIdNote(Integer idNote) {
		this.idNote = idNote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sawapnID", nullable = false)
	public Swapper getSwapper() {
		return this.swapper;
	}

	public void setSwapper(Swapper swapper) {
		this.swapper = swapper;
	}

	@Column(name = "note", nullable = false)
	public int getNote() {
		return this.note;
	}

	public void setNote(int note) {
		this.note = note;
	}

}
