package tn.esprit.persistance;
// Generated 19 nov. 2016 13:17:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "troc")
public class Service implements java.io.Serializable {

	private Integer idService;
	private Subcategory subcategory;
	private Swapper swapper;
	private String label;
	private String description;
	private String disponibility;
	private int validity;
	private Date date;
	private String imgPath;
	private int score;
	private Set<Exchangeservice> exchangeservicesForIdserviceOffre = new HashSet<Exchangeservice>(0);
	private Set<Exchangeservice> exchangeservicesForIdExchange = new HashSet<Exchangeservice>(0);
	private static final long serialVersionUID = 1L;
	
	public Service() {
	}

	public Service(Swapper swapper, int validity, Date date, int score) {
		this.swapper = swapper;
		this.validity = validity;
		this.date = date;
		this.score = score;
	}

	public Service(Subcategory subcategory, Swapper swapper, String label, String description, String disponibility,
			int validity, Date date, String imgPath, int score, Set<Exchangeservice> exchangeservicesForIdserviceOffre,
			Set<Exchangeservice> exchangeservicesForIdExchange) {
		this.subcategory = subcategory;
		this.swapper = swapper;
		this.label = label;
		this.description = description;
		this.disponibility = disponibility;
		this.validity = validity;
		this.date = date;
		this.imgPath = imgPath;
		this.score = score;
		this.exchangeservicesForIdserviceOffre = exchangeservicesForIdserviceOffre;
		this.exchangeservicesForIdExchange = exchangeservicesForIdExchange;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_service", unique = true, nullable = false)
	public Integer getIdService() {
		return this.idService;
	}

	public void setIdService(Integer idService) {
		this.idService = idService;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subCategory_id_subCategory")
	public Subcategory getSubcategory() {
		return this.subcategory;
	}

	public void setSubcategory(Subcategory subcategory) {
		this.subcategory = subcategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "swapperID", nullable = false)
	public Swapper getSwapper() {
		return this.swapper;
	}

	public void setSwapper(Swapper swapper) {
		this.swapper = swapper;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "disponibility")
	public String getDisponibility() {
		return this.disponibility;
	}

	public void setDisponibility(String disponibility) {
		this.disponibility = disponibility;
	}

	@Column(name = "validity", nullable = false)
	public int getValidity() {
		return this.validity;
	}

	public void setValidity(int validity) {
		this.validity = validity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "imgPath")
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceByIdserviceOffre")
	public Set<Exchangeservice> getExchangeservicesForIdserviceOffre() {
		return this.exchangeservicesForIdserviceOffre;
	}

	public void setExchangeservicesForIdserviceOffre(Set<Exchangeservice> exchangeservicesForIdserviceOffre) {
		this.exchangeservicesForIdserviceOffre = exchangeservicesForIdserviceOffre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceByIdExchange")
	public Set<Exchangeservice> getExchangeservicesForIdExchange() {
		return this.exchangeservicesForIdExchange;
	}

	public void setExchangeservicesForIdExchange(Set<Exchangeservice> exchangeservicesForIdExchange) {
		this.exchangeservicesForIdExchange = exchangeservicesForIdExchange;
	}

}
