package tn.esprit.persistance;
// Generated 19 nov. 2016 13:17:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subcategory generated by hbm2java
 */
@Entity
@Table(name = "subcategory", catalog = "troc")
public class Subcategory implements java.io.Serializable {

	private Integer idSubCategory;
	private Category category;
	private String name;
	private String description;
	private Date creationDate;
	private Set<Goods> goodses = new HashSet<Goods>(0);
	private Set<Service> services = new HashSet<Service>(0);
	private static final long serialVersionUID = 1L;
	
	public Subcategory() {
	}

	public Subcategory(Category category, Date creationDate) {
		this.category = category;
		this.creationDate = creationDate;
	}

	public Subcategory(Category category, String name, String description, Date creationDate, Set<Goods> goodses,
			Set<Service> services) {
		this.category = category;
		this.name = name;
		this.description = description;
		this.creationDate = creationDate;
		this.goodses = goodses;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_subCategory", unique = true, nullable = false)
	public Integer getIdSubCategory() {
		return this.idSubCategory;
	}

	public void setIdSubCategory(Integer idSubCategory) {
		this.idSubCategory = idSubCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryID", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcategory")
	public Set<Goods> getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set<Goods> goodses) {
		this.goodses = goodses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcategory")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
